version: '2'
services:

  devcontainer:
    build:
      context: .
      args:
        DBT_VERSION: 1.0.0
    volumes:
      - .:/workspaces/jaffle_shop_dbtvault/
    ports:
      - 8080:8080

  postgres:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
    ports:
      - 6432:5432

